dictionary = {
    "Rage": "in battle, you fight with a primal ferocity. On your turn, you can enter a rage as a bonus action.  While raging, you gain the following benefits, as long as you aren't wearing heavy armor. \n\tYou have advantage on Strength check and Strength saves. \n\tWhen you make a melee weapon attack using Strength, you gain a +2 to the damage roll. This bonus  increase to +3 at 9th level, and +4 at 16th level. \n\tYou have resistance to bludgeoning, piercing, and physical damage. \nIf you can cast spells, you can't cast them or concentrate on them while raging. \nYour rage lasts 1 minute. It ends early if you are knocked unconscious  or if your turn ends without you having attacked a hostile creature or taken any damage since your  last turn.  You can also end your rage on your turn as a bonus action. \nOnce you have raged a number of time shown for your barbarian level on the table above,  you must finish a long rest before you can rage again.",
    "Unarmored Defense": "When you aren't wearing any armor,  your Armor Class is 10 + your Dexterity modifier + your Constitution modifier.  You can use a shield and still gain this benefit.",
    "Reckless Attack": "At 2nd level, you can throw aside all concern for defense to attack with fierce desperation.  When you make your first attack on your turn, you can decide to attack recklessly.  Doing so gives you advantage on melee weapon attack rolls using Strength during this turn,  but attack rolls against you have advantage until your next turn.",
    "Danger Sense": "You have advantage on Dexterity saving throws against effects that you can see,  such as traps and spells.  To gain this benefit, you can't be blinded, deafened, or incapacitated.",
    "Extra Attack": "allows you to make one additional attack when you take the Attack action. (You may also move between the two attacks)" ,
    "Fast Movement": "your speed increases by 10 feet while you aren't wearing Heavy Armor." ,
    "Relentless Rage": "Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you're raging and don't die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead.Each time you use this feature after the first, the DC increases by 5. When you finish a short or Long Rest, the DC resets to 10." ,
    "Persistant Rage": "Beginning at 15th level, your rage is so fierce that it ends early only if you fall Unconscious or if you choose to end it." ,
    "Indomitable Might": "Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total." ,
    "Primal Champion": "At 20th level, you embody the power of the wilds. Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24." ,
    "All Consuming Rage": "Starting at 3rd level, during rage, when you reduce a hostile opponent to 0 hit points, you gain temporary hit points equal your Constitution modifier + your barbarian level  (minimum of 1).",
    "Biting Rebuke": "At 6th level, while in rage you can make a bite attack as a reaction when struck in melee by an opponent.  This attack deals 1d4 + Strength modifier damage,  and on a hit the opponent must succeed on a wisdom save DC 16 or be frightened,  they may retest at the beginning of their next turn to overcome the frightened condition.",
    "Heart of Enemies": "by consuming a heart of a humanoid you have participated in slaying within the past hour,  you regain your full hit points as if finishing a long rest.  You must finish a long rest to regain use of this feature.",
    "Spirit of the Slain": "At 14th level, by channeling the spirits of those you have eaten,  you have advantage on your next attack.  You can only do this a number of times each day equal to your proficiency bonus,  and only once per turn.",
    "Ancestral Protectors": "Starting when you choose this path at 3rd level,  spectral warriors appear when you enter your rage.  While you're raging, the first creature you hit with an attack on your "
                            "turn becomes  the target of the warriors, which hinder its attacks.  Until the start of your next turn, that target has disadvantage on any attack roll  that isn't against you, and when the target hits a creature other than you with an attack,  that creature has resistance to the damage dealt by the attack.  The effect on the target ends early if your rage ends.",
    "Spirit Shield": "If you are raging and another creature you can see within 30 feet of you takes damage,  you can use your reaction to reduce that damage by 1d6, 2d6 above level 6, 3d6 above level 10, or 4d6 above level 14",
    "Consult the Spirit": "At 10th level, you gain the ability to consult with your ancestral spirits.  When you do so, you cast the augury or clairvoyance spell,  without using a spell slot or material components.  Rather than creating a spherical sensor,  this use of clairvoyance invisibly summons one Of your ancestral spirits  to the chosen location. Wisdom is your spellcasting ability for these spells.  After you cast either spell in this way, you can't use this feature again until you  finish a short or long rest.",
    "Vengeful Ancestors": "At 14th level, your ancestral spirits grow powerful enough to retaliate.  When you use your Spirit Shield to reduce the damage of an attack,  the attacker takes an amount of force damage equal to the damage  that your Spirit Shield prevents.",
    "Battlerager Armor": "When you choose this path at 3rd level, you gain the ability to use spiked armor (see the 'Spiked  Armor' sidebar) as a weapon. While you are wearing spiked armor and are raging, you can use a  bonus action to make one melee weapon attack with your armor spikes against a target within 5  feet of you. If the attack hits,/ the spikes deal ld4 piercing damage. You use your Strength  modifier for the attack and damage rolls. Additionally, when you use the Attack action to grapple  a creature, the target takes 3 piercing damage if your grapple c",
    "Reckless Abandon": "Beginning at 6th level, when you use Reckless Attack while raging, "
                        "you also gain temporary hit  points equal to your Constitution modifier (minimum of 1). They vanish if any of them are left  when your rage ends. ",
    "Battlerager Charge": "Beginning at 10th level, you can take the Dash action as a bonus action while raging." ,
    "Spiked Retribution": "Starting at 14th level, when a creature within 5 feet of you hits you with a melee attack, the attacker takes 3 piercing damage if you are raging, aren't incapacitated, and are wearing spiked armor." ,
    "Frenzy": "Starting when you choose this path at 3rd level, you can go into a frenzy when you rage. If you  do so, for the duration of your rage you can make a single melee weapon attack as a bonus action  on each of your turns after this one. When your rage ends, you suffer one level of exhaustion.",
    "Intimidating Presence": "Beginning at 10th level, you can use your action to frighten someone with your menacing  presence. When you do so, choose one creature that you can see within 30 feet of you. If the  creature can see or hear you, it must succeed on a Wisdom saving throw with dc 8 + prof + charisma or be frightened of you until the end of your next turn. On subsequent turns, you can use your  action to extend the duration of this effect on the frightened creature until the end of your next  turn. This effect ends if the creature ends its turn out of line of sight or more than 60 feet  away from you. ",
    "Retaliation": "when you take damage from a creature that is within 5 feet of you, you can use your reaction to  make a melee weapon attack against that creature.",
    "Divine Fury": "you can channel divine fury into your weapon strikes. While you're raging, "
                   "the first creature you  hit on each of your turns with a weapon attack takes extra damage equal to 1d6 "
                   "+ level / 2 The extra damage is necrotic or radiant; you choose the type of "
                   "damage when you gain this feature.",
    "Warrior of the Gods": "If a spell, such as raise dead, has the sole effect of restoring you to "
                           "life (but not uncleath),  the caster doesn't need material components to cast the spell on you. ",
    "Fanatical Focus": "the divine power that fuels your rage can protect you. If you fail a saving "
                       "throw while you're  raging, you can reroll it, and you must use the new roll. You can use this "
                       "ability only once per  rage. ",
    "Zealous Presence": "you learn to channel divine power to inspire zealotry in others. As a "
                        "bonus action, you unleash a  battle cry infused with divine energy. Up to ten other creatures of your "
                        "choice within 60 feet of  you that can hear you gain advantage on attack rolls and saving throws "
                        "until the start of your  next turn. Once you use this feature, you can't use it again until you "
                        "finish a long rest. ",
    "Rage Beyond Death": "the divine power that fuels your rage allows you to shrug off fatal "
                         "blows. While you're raging,  having 0 hit points doesn't knock you unconscious. You still must make "
                         "death saving throws,  and you suffer the normal effects of taking damage while at 0 hit points. "
                         "However, if you would  die due to failing death saving throws, you don't die until your rage "
                         "ends, and you die then only  if you still have 0 hit points. ",
    "Ritual Casting": "You can cast any bard spell you know as a ritual if that spell has the ritual tag." ,
    "Spellcasting Focus": "You can use a musical instrument as a spellcasting focus for your bard spells",
    "Bardic Inspiration": "You can use a bonus action on your turn to choose one creature other than yourself within 60 feet of you who can hear you. That creature gains one Bardic Inspiration die, a d6.\nOnce within the next 10 minutes, the creature can roll the die and add the number rolled to one ability check, attack roll, or saving throw it makes. The creature can wait until after it rolls the d20 before deciding to use the Bardic Inspiration die, but must decide before the DM says whether the roll succeeds or fails. Once the Bardic Inspiration die is rolled, it is lost. A creature can have only one Bardic Inspiration die at a time.\n You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain any expended uses when you finish a long rest. Your Bardic Inspiration die changes when you reach certain levels in this class. The die becomes a d8 at 5th level, a d10 at 10th level, and a d12 at 15th level.",
    "Jack of all Trades": "you can add half your proficiency bonus, rounded down, to any ability check you make that doesn't already include your proficiency bonus.",
    "Song of Rest": "if you or any friendly creatures who can hear you make a performance regain hit points by spending hit dice at the end of the short rest, each of those creatures regains an extra 1d6 hit points.\nThe extra hit points increase when you reach certain levels in this class: to 1d8 at 9th level, to 1d10 at 13th level, and to 1d12 at 17th level.",
    "Expertise": "At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies. At 10th level, you can choose another two skill proficiencies to gain this benefit.",
    "Font of Inspiration": "Beginning when you reach 5th level, you regain all of your expended uses of Bardic Inspiration when you finish a short or long rest.",
    "Countercharm": "At 6th level, as an action, you can start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 30 feet of you have advantage on saving throws against being frightened or charmed. A creature must be able to hear you to gain this benefit. The performance ends early if you are incapacitated or silenced or if you voluntarily end it (no action required).",
    "Magical Secrets": "By 10th level, choose two spells from any class, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip.\nThe chosen spells count as bard spells for you and are included in the number in the spells known column of the Bard table.\nYou learn two additional spells from any class at 14th level and again at 18th level.",
    "Superior Inspiration": "At 20th level, when you roll initiative and have no uses of Bardic Inspiration left, you regain one use.",
    "Mantle of Inspiration": "At 3rd level, as a bonus action, you can expend one use of your Bardic Inspiration to grant yourself a wondrous appearance. When you do so, choose a number of creatures you can see and that can see you within 60 feet of you, up to a number equal to your Charisma modifier (minimum of one). Each of them gains 5 temporary hit points. When a creature gains these temporary hit points, it can immediately use its reaction to move up to its speed, without provoking opportunity attacks.\nThe number of temporary hit points increases when you reach certain levels in this class, increasing to 8 at 5th level, 11 at 10th level, and 14 at 15th level.",
    "Enthralling Performance": "Starting at 3rd level, if you perform for at least 1 minute, you can attempt to inspire wonder in your audience. At the end of the performance, choose a number of humanoids within 60 feet of you who watched and listened to all of it, up to a number equal to your Charisma modifier (minimum of one). Each target must succeed on a Wisdom saving throw against your spell save DC or be charmed by you. While charmed in this way, the target idolizes you, it speaks glowingly of you to anyone who talks to it, and it hinders anyone who opposes you, although it avoids violence unless it was already inclined to fight on your behalf. This effect ends on a target after 1 hour, if it takes any damage, if you attack it, or if it witnesses you attacking or damaging any of its allies. \nIf a target succeeds on its saving throw, the target has no hint that you tried to charm it. \nOnce you use this feature, you can't use it again until you finish a short or long rest. ",
    "Mantle of Majesty": "At 6th level, as a bonus action, you cast Command, without expending a spell slot, and you take on an appearance of unearthly beauty for 1 minute or until your concentration ends (as if you were concentrating on a spell). During this time, you can cast Command as a bonus action on each of your turns, without expending a spell slot.\nAny creature charmed by you automatically fails its saving throw against the Command you cast with this feature.\nOnce you use this feature, you can't use it again until you finish a long rest.",
    "Unbreakable Majesty": "At 14th level, as a bonus action, you can assume a magically majestic presence for 1 minute or until you are incapacitated. For the duration, whenever any creature tries to attack you for the first time on a turn, the attacker must make a Charisma saving throw against your spell save DC. On a failed save, it can't attack you on this turn, and it must choose a new target for its attack or the attack is wasted. On a successful save, it can attack you on this turn, but it has disadvantage on any saving throw it makes against your spells on your next turn.\nOnce you assume this majestic presence, you can't do so again until you finish a short or long rest.  ",
    "Cutting Words": "Also at 3rd level, when a creature that you can see within 60 feet of you makes an attack roll, an ability check, or a damage roll, you can use your reaction to expend one of your uses of Bardic Inspiration, rolling a Bardic Inspiration die and subtracting the number rolled from the creature's roll. You can choose to use this feature after the creature makes its roll, but before the DM determines whether the attack roll or ability check succeeds or fails, or before the creature deals its damage. The creature is immune if it can't hear you or if it's immune to being charmed.",
    "Additional Magical Secrets": "At 6th level, you learn two spells of your choice from any class. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip. The chosen spells count as bard spells for you but don't count against the number of bard spells you know.",
    "Peerless Skill": "Starting at 14th level, when you make an ability check, you can expend one use of Bardic Inspiration. Roll a Bardic Inspiration die and add the number rolled to your ability check. You can choose to do so after you roll the die for the ability check, but before the GM tells you whether you succeed or fail.",
    "Tumbling Fool": "At 3rd level, as a bonus action, you can tumble. When you tumble, you gain the following benefits for the rest of your turn:\nYou gain the benefits of taking the Dash and Disengage actions.\nYou gain a climbing speed equal to your current speed.\nYou take half damage from falling.",
    "Fool's Insight": "At 6th level, you can cast Detect Thoughts up to a number of times equal to your Charisma modifier. You regain any expended uses of this ability after completing a long rest.\nIf a creature resists your attempt to probe deeper and succeeds at its saving throw against your Detect Thoughts, it immediately suffers an embarrassing social gaffe.",
    "Fool's Luck": "At 14th level, you can expend one use of Bardic Inspiration after you fail an ability check, fail a saving throw, or miss with an attack roll. Roll a Bardic Inspiration die and add the number rolled to your attack, saving throw, or ability check, using the new result in place of the failed one.\nIf using this ability grants you a success on the attack, saving throw, or ability check, note the number you rolled on the Bardic Inspiration die. The DM can then apply that result as a penalty to an attack or check you make, and you cannot use this ability again until you suffer this drawback. When the DM invokes this penalty, describe an embarrassing gaffe or mistake you make as part of the affected die roll.",
    "Dueling (Bard)": "When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.",
    "Two-Weapon Fighting (Bard)": "When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.",
    "Blade Flourish": "At 3rd level, whenever you take the Attack action on your turn, your walking speed increases by 10 feet until the end of the turn, and if a weapon attack that you make as part of this action hits a creature, you can use one of the following Blade Flourish options of your choice. You can use only one Blade Flourish option per turn.\nDefensive Flourish: You can expend one use of your Bardic Inspiration to cause the weapon to deal extra damage to the target you hit. The damage equals the number you roll on the Bardic Inspiration die. You also add the number rolled to your AC until the start of your next turn.\nSlashing Flourish: You can expend one use of your Bardic Inspiration to cause the weapon to deal extra damage to the target you hit and to any other creature of your choice that you can see within 5 feet of you. The damage equals the number you roll on the Bardic Inspiration die.\nMobile Flourish: You can expend one use of your Bardic Inspiration to cause the weapon to deal extra damage to the target you hit. The damage equals the number you roll on the Bardic Inspiration die. You can also push the target up to 5 feet away from you, plus a number of feet equal to the number you roll on that die. You can then immediately use your reaction to move up to your walking speed to an unoccupied space within 5 feet of the target. ",
    "Master's Flourish": "Starting at 14th level, whenever you use a Blade Flourish option, you can roll a d6 and use it instead of expending a Bardic Inspiration die.",
    "Combat Inspiration": "Also at 3rd level, a creature that has a Bardic Inspiration die from you can roll that die and add the number rolled to a weapon damage roll it just made. Alternatively, when an attack roll is made against the creature, it can use its reaction to roll the Bardic Inspiration die and add the number rolled to its AC against that attack, after seeing the roll but before knowing whether it hits or misses.",
    "Battle Magic": "At 14th level, when you use your action to a cast a bard spell, you can make one weapon attack as a bonus action.",
    "Psychic Blades": "At 3rd level, when you hit a creature with a weapon attack, you can expend one use of your Bardic Inspiration to deal an extra 2d6 psychic damage to that target. You can do so only once per round on your turn.\nThe psychic damage increases when you reach certain levels in this class, increasing to 3d6 at 5th level, 5d6 at 10th level, and 8d6 at 15th level.",
    "Words of Terror": "At 3rd level, if you speak to a humanoid alone for at least 1 minute, you can attempt to seed paranoia in its mind. At the end of the conversation, the target must succeed on a Wisdom saving throw against your spell save DC or be frightened of you or another creature of your choice. The target is frightened in this way for 1 hour, until it is attacked or damaged, or until it witnesses its allies being attacked or damaged. \nIf the target succeeds on its saving throw, the target has no hint that you tried to frighten it. \nOnce you use this feature, you can't use it again until you finish a short or long rest. ",
    "Mantle of Whispers": "At 6th level, when a humanoid dies within 30 feet of you, you can magically capture its shadow using your reaction. You retain this shadow until you use it or you finish a long rest.You can use the shadow as an action. When you do so, it vanishes, magically transforming into a disguise that appears on you. You now look like the dead person, but healthy and alive. This disguise lasts for 1 hour or until you end it as a bonus action.\nWhile you're in the disguise, you gain access to all information that the humanoid would freely share with a casual acquaintance. Such information includes general details on its background and personal life, but doesn't include secrets. The information is enough that you can pass yourself off as the person by drawing on its memories.\nAnother creature can see through this disguise by succeeding on a Wisdom (Insight) check contested by your Charisma (Deception) check. You gain a +5 bonus to your check.\nOnce you capture a shadow with this feature, you can't capture another one with it until you finish a short or long rest.",
    "Shadow Lore": "At 14th level, as an action, you magically whisper a phrase that only one creature of your choice within 30 feet of you can hear. The target must make a Wisdom saving throw against your spell save DC. It automatically succeeds if it doesn't share a language with you or if it can't hear you. On a successful saving throw, your whisper sounds like unintelligible mumbling and has no effect.\nOn a failed saving throw, the target is charmed by you for the next 8 hours or until you or your allies attack it, damage it, or force it to make a saving throw. It interprets the whispers as a description of its most mortifying secret. You gain no knowledge of this secret, but the target is convinced you know it.\nThe charmed creature obeys your commands for fear that you will reveal its secret. It won't risk its life for you or fight for you, unless it was already inclined to do so. It grants you favors and gifts it would offer to a close friend.\nWhen the effect ends, the creature has no understanding of why it held you in such fear.\nOnce you use this feature, you can't use it again until you finish a long rest.",
    "": "",
}